# Generated by Django 3.2.3 on 2021-05-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards_app', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='author',
            new_name='user',
        ),
    ]
